In [97]:
# Cargar los modulos mas comunes, con sus alias
import numpy as pd
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [98]:
# Descargar el CSV desde datos
!wget -O covid.csv 'https://www.datos.gov.co/resource/gt2j-8ykr.csv?$limit=1000'

--2021-06-23 01:10:37--  https://www.datos.gov.co/resource/gt2j-8ykr.csv?$limit=1000
Resolving www.datos.gov.co (www.datos.gov.co)... 52.206.140.205
Connecting to www.datos.gov.co (www.datos.gov.co)|52.206.140.205|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/csv]
Saving to: ‘covid.csv’

covid.csv               [ <=>                ] 209.60K  --.-KB/s    in 0.007s

2021-06-23 01:10:38 (27.7 MB/s) - ‘covid.csv’ saved [214628]

In [99]:
 !wget -O covid.csv !wget -O covid.csv https://www.datos.gov.co/api/views/gt2j-8ykr/rows.csv?accessType=DOWNLOAD

--2021-06-23 01:10:38--  http://!wget/
Resolving !wget (!wget)... failed: Name or service not known.
wget: unable to resolve host address ‘!wget’
--2021-06-23 01:10:38--  https://www.datos.gov.co/api/views/gt2j-8ykr/rows.csv?accessType=DOWNLOAD
Resolving www.datos.gov.co (www.datos.gov.co)... 52.206.140.205
Connecting to www.datos.gov.co (www.datos.gov.co)|52.206.140.205|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/csv]
Saving to: ‘covid.csv’

covid.csv               [   <=>              ] 652.32M  5.90MB/s    in 2m 7s

2021-06-23 01:12:45 (5.13 MB/s) - ‘covid.csv’ saved [684003027]

FINISHED --2021-06-23 01:12:45--
Total wall clock time: 2m 7s
Downloaded: 1 files, 652M in 2m 7s (5.13 MB/s)

In [100]:
# Cargar el CSD desde datos.gov.co en un dataframe
covid = pd.read_csv('covid.csv')

/home/ubuntu/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (14,17,19,20,22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [101]:
# Revisar el dataframe
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3968405 entries, 0 to 3968404
Data columns (total 23 columns):
 #   Column                        Dtype
---  ------                        -----
 0   fecha reporte web             object
 1   ID de caso                    int64
 2   Fecha de notificación         object
 3   Código DIVIPOLA departamento  int64
 4   Nombre departamento           object
 5   Código DIVIPOLA municipio     int64
 6   Nombre municipio              object
 7   Edad                          int64
 8   Unidad de medida de edad      int64
 9   Sexo                          object
 10  Tipo de contagio              object
 11  Ubicación del caso            object
 12  Estado                        object
 13  Código ISO del país           float64
 14  Nombre del país               object
 15  Recuperado                    object
 16  Fecha de inicio de síntomas   object
 17  Fecha de muerte               object
 18  Fecha de diagnóstico          object
 19  Fecha de recuperación         object
 20  Tipo de recuperación          object
 21  Pertenencia étnica            float64
 22  Nombre del grupo étnico       object
dtypes: float64(2), int64(5), object(16)
memory usage: 696.4+ MB

In [102]:
covid.columns

Index(['fecha reporte web', 'ID de caso', 'Fecha de notificación',
       'Código DIVIPOLA departamento', 'Nombre departamento',
       'Código DIVIPOLA municipio', 'Nombre municipio', 'Edad',
       'Unidad de medida de edad', 'Sexo', 'Tipo de contagio',
       'Ubicación del caso', 'Estado', 'Código ISO del país',
       'Nombre del país', 'Recuperado', 'Fecha de inicio de síntomas',
       'Fecha de muerte', 'Fecha de diagnóstico', 'Fecha de recuperación',
       'Tipo de recuperación', 'Pertenencia étnica',
       'Nombre del grupo étnico'],
      dtype='object')

In [103]:
covid.shape

(3968405, 23)

In [104]:
covid.head()

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
0,6/3/2020 0:00:00,1,2/3/2020 0:00:00,11,BOGOTA,11001,BOGOTA,19,1,F,...,380.0,ITALIA,Recuperado,27/2/2020 0:00:00,NaN,6/3/2020 0:00:00,13/3/2020 0:00:00,PCR,6.0,NaN
1,9/3/2020 0:00:00,2,6/3/2020 0:00:00,76,VALLE,76111,BUGA,34,1,M,...,724.0,ESPAÑA,Recuperado,4/3/2020 0:00:00,NaN,9/3/2020 0:00:00,19/3/2020 0:00:00,PCR,5.0,NaN
2,9/3/2020 0:00:00,3,7/3/2020 0:00:00,5,ANTIOQUIA,5001,MEDELLIN,50,1,F,...,724.0,ESPAÑA,Recuperado,29/2/2020 0:00:00,NaN,9/3/2020 0:00:00,15/3/2020 0:00:00,PCR,6.0,NaN
3,11/3/2020 0:00:00,4,9/3/2020 0:00:00,5,ANTIOQUIA,5001,MEDELLIN,55,1,M,...,NaN,NaN,Recuperado,6/3/2020 0:00:00,NaN,11/3/2020 0:00:00,26/3/2020 0:00:00,PCR,6.0,NaN
4,11/3/2020 0:00:00,5,9/3/2020 0:00:00,5,ANTIOQUIA,5001,MEDELLIN,25,1,M,...,NaN,NaN,Recuperado,8/3/2020 0:00:00,NaN,11/3/2020 0:00:00,23/3/2020 0:00:00,PCR,6.0,NaN

In [105]:
covid.tail()

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
3968400,21/6/2021 0:00:00,3968441,17/6/2021 0:00:00,8001,BARRANQUILLA,8001,BARRANQUILLA,14,1,F,...,NaN,NaN,Activo,13/6/2021 0:00:00,NaN,17/6/2021 0:00:00,NaN,NaN,NaN,NaN
3968401,21/6/2021 0:00:00,3968442,18/6/2021 0:00:00,8001,BARRANQUILLA,8001,BARRANQUILLA,44,1,M,...,NaN,NaN,Activo,14/6/2021 0:00:00,NaN,18/6/2021 0:00:00,NaN,NaN,NaN,NaN
3968402,21/6/2021 0:00:00,3968443,18/6/2021 0:00:00,8001,BARRANQUILLA,8001,BARRANQUILLA,21,1,M,...,NaN,NaN,Activo,14/6/2021 0:00:00,NaN,18/6/2021 0:00:00,NaN,NaN,NaN,NaN
3968403,21/6/2021 0:00:00,3968444,18/6/2021 0:00:00,8001,BARRANQUILLA,8001,BARRANQUILLA,28,1,M,...,NaN,NaN,Activo,14/6/2021 0:00:00,NaN,18/6/2021 0:00:00,NaN,NaN,NaN,NaN
3968404,21/6/2021 0:00:00,3968445,17/6/2021 0:00:00,8001,BARRANQUILLA,8001,BARRANQUILLA,43,1,F,...,NaN,NaN,Activo,13/6/2021 0:00:00,NaN,17/6/2021 0:00:00,NaN,NaN,NaN,NaN

In [106]:
covid['edad'].describe()

KeyError: 'edad'

In [ ]:
#Seleccionar solo algunas columnas de interes
covid[['ciudad_municipio_nom','sexo', 'edad']]

In [ ]:
cd['count']

In [ ]:
#Ordenar por dos columnas 
covid.sort_value(by=['ciudad_municipio_nom', 'edad'], ascending=True)

In [ ]:
#Cuantas personas con sus edaddes, hay infectadas por municipios?
c2 = covid[['ciudad_municipio_nom'], 'sexo', 'edad']]
c2.sort_values(by=[])

In [ ]:
cf['acumulados'] = cf['count'].cumsum()